spring:
  application:
    name: demo
esign-v3:
  configs:
    - name: app1
      app-id: your app id
      secret: your app secret
      sandbox: true
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    io.github.easy.esign: info

